ph-ee-g2psandbox:
  ph-ee-engine:
  
    elasticsearch:
      volumeClaimTemplate:
        storageClassName: "local-path"
    
    notifications:
      limits:
        cpu: "1000m"
        memory: "2000M"
      requests:
        cpu: "1m"
        memory: "1M"

    operations_web:
      ingress:
        enabled: true
    
    operations_app:
      limits:
        cpu: "1000m"
        memory: "2000M"
      requests:
        cpu: "1m"
        memory: "1M" 